Repository MathewSachin/Captura, pull requests merged in 2018-10, with the labels that each got.

#275 Custom Expander Style
  src/Captura/App.xaml
  src/Captura/Captura.csproj
  src/Captura/Pages/MainPage.xaml
  src/Captura/Presentation/MaterialDesignIcons.xaml
  src/Captura/Presentation/Themes/Expander.xaml
  src/Captura/Windows/MainWindow.xaml
Labels: enhancement

#278 Split Cake Script into include files
  .gitignore
  appveyor.yml
  build.cake
  tools/scripts/apikeys.cake
  tools/scripts/appveyor.cake
  tools/scripts/backup.cake
  tools/scripts/bass.cake
  tools/scripts/choco.cake
  tools/scripts/constants.cake
  tools/scripts/version.cake
Labels: enhancement

#279 FFmpeg Args Builder
  src/Captura.FFmpeg/ArgsBuilder/FFmpegArgs.cs
  src/Captura.FFmpeg/ArgsBuilder/FFmpegArgsBuilder.cs
  src/Captura.FFmpeg/ArgsBuilder/FFmpegInputArgs.cs
  src/Captura.FFmpeg/ArgsBuilder/FFmpegOutputArgs.cs
  src/Captura.FFmpeg/Audio/FFmpegAudioWriter.cs
  src/Captura.FFmpeg/Captura.FFmpeg.csproj
  src/Captura.FFmpeg/Video/FFMpegPostProcessingWriter.cs
  src/Captura.FFmpeg/Video/FFmpegVideoWriter.cs
Labels: enhancement

#280 Fix coordinate transform for full screen items
  src/Screna/VideoItems/FullScreenItem.cs
Labels: bug

#274 Sounds
  src/Captura.Base/Audio/SoundKind.cs
  src/Captura.Base/Captura.Base.csproj
  src/Captura.Base/Services/IAudioPlayer.cs
  src/Captura.Core/Captura.Core.csproj
  src/Captura.Core/CoreModule.cs
  src/Captura.Core/Fakes/FakeAudioPlayer.cs
  src/Captura.Core/Fakes/FakesModule.cs
  src/Captura.Core/Settings/Models/SoundSettings.cs
  src/Captura.Core/Settings/Settings.cs
  src/Captura.Core/ViewModels/RecordingViewModel.cs
  src/Captura.Core/ViewModels/ScreenShotViewModel.cs
  src/Captura.Core/ViewModels/SoundsViewModel.cs
  src/Captura.Core/ViewModels/SoundsViewModelItem.cs
  src/Captura/Captura.csproj
  src/Captura/Models/AudioPlayer.cs
  src/Captura/Models/MainModule.cs
  src/Captura/Models/MessageProvider.cs
  src/Captura/Models/ServiceLocator.cs
  src/Captura/Models/SystemTray.cs
  src/Captura/Pages/ConfigPage.xaml
  src/Captura/Pages/ConfigPage.xaml.cs
  src/Captura/Windows/SoundsWindow.xaml
  src/Captura/Windows/SoundsWindow.xaml.cs
Labels: enhancement

#282 Cmdline Window, Screen capture fix
  src/Captura.Console/Program.cs
  src/Captura.Core/Fakes/FakeVideoSourcePicker.cs
  src/Captura.Core/Fakes/FakesModule.cs
Labels: bug

#289 New Crowdin translations
  src/Captura.Loc/Languages/ar.json
  src/Captura.Loc/Languages/be.json
  src/Captura.Loc/Languages/cs.json
  src/Captura.Loc/Languages/da.json
  src/Captura.Loc/Languages/de.json
  src/Captura.Loc/Languages/en.json
  src/Captura.Loc/Languages/es.json
  src/Captura.Loc/Languages/fi.json
  src/Captura.Loc/Languages/fr.json
  src/Captura.Loc/Languages/he.json
  src/Captura.Loc/Languages/id.json
  src/Captura.Loc/Languages/is.json
  src/Captura.Loc/Languages/it.json
  src/Captura.Loc/Languages/ja.json
  src/Captura.Loc/Languages/kab.json
  src/Captura.Loc/Languages/ml.json
  src/Captura.Loc/Languages/nl.json
  src/Captura.Loc/Languages/no.json
  src/Captura.Loc/Languages/pl.json
  src/Captura.Loc/Languages/pt.json
  src/Captura.Loc/Languages/ro.json
  src/Captura.Loc/Languages/ru.json
  src/Captura.Loc/Languages/sl.json
  src/Captura.Loc/Languages/sv.json
  src/Captura.Loc/Languages/th.json
  src/Captura.Loc/Languages/tr.json
  src/Captura.Loc/Languages/uk.json
  src/Captura.Loc/Languages/vi.json
  src/Captura.Loc/Languages/zh-CN.json
  src/Captura.Loc/Languages/zh-TW.json
Labels: translation

#290 New Crowdin translations
  src/Captura.Loc/Languages/hi.json
  src/Captura.Loc/Languages/ml.json
  src/Captura.Loc/Languages/uk.json
Labels: translation

#294 Use Cake as dotnet tool
  .gitignore
  appveyor.yml
  build.cake
  build.ps1
  scripts/version.cake
  tools/packages.config
Labels: enhancement

#291 Update Localization
  src/Captura.Core/Models/ImageWriterItems/ImgurWriter.cs
  src/Captura.Core/ViewModels/VideoViewModel.cs
  src/Captura.Loc/Captura.Loc.csproj
  src/Captura.Loc/LanguageField.cs
  src/Captura.Loc/LanguageFields.cs
  src/Captura.Loc/Languages/en.json
  src/Captura.Loc/TranslationViewModel.cs
  src/Captura/Captura.csproj
  src/Captura/Controls/NotificationStack.xaml
  src/Captura/Controls/RecentItem.xaml
  src/Captura/Controls/TextOverlaySettingsControl.xaml
  src/Captura/ImageEditor/ImageEditorWindow.xaml
  src/Captura/Pages/AboutPage.xaml
  src/Captura/Pages/AboutPage.xaml.cs
  src/Captura/Pages/AudioPage.xaml
  src/Captura/Pages/CensorOverlaysPage.xaml
  src/Captura/Pages/ConfigPage.xaml
  src/Captura/Pages/ExtrasPage.xaml
  src/Captura/Pages/FFmpegPage.xaml
  src/Captura/Pages/KeystrokesPage.xaml
  src/Captura/Pages/MainPage.xaml
  src/Captura/Pages/MouseOverlayPage.xaml
  src/Captura/Pages/ScreenShotsPage.xaml
  src/Captura/Pages/TextOverlaysPage.xaml
  src/Captura/Pages/VideoPage.xaml
  src/Captura/Pages/WebcamPage.xaml
  src/Captura/Windows/CrashLogsWindow.xaml
  src/Captura/Windows/CropWindow.xaml
  src/Captura/Windows/ExceptionWindow.xaml
  src/Captura/Windows/HotkeysWindow.xaml
  src/Captura/Windows/OverlayWindow.xaml
  src/Captura/Windows/PreviewWindow.xaml
  src/Captura/Windows/RegionSelector.xaml
  src/Captura/Windows/TranslationWindow.xaml
  src/Captura/Windows/TranslationWindow.xaml.cs
  src/DesktopDuplication/DeskDuplSourceProvider.cs
  src/Screna/Gif/GifWriterProvider.cs
Labels: translation

#301 Customizable Tray Left Click Action
  src/Captura.Core/Settings/Models/VisualSettings.cs
  src/Captura.Core/ViewModels/MainViewModel.cs
  src/Captura.Hotkeys/HotKeyManager.cs
  src/Captura.Loc/LanguageFields.cs
  src/Captura.Loc/Languages/en.json
  src/Captura/Captura.csproj
  src/Captura/Pages/ConfigPage.xaml
  src/Captura/Pages/ConfigPage.xaml.cs
  src/Captura/Windows/MainWindow.xaml
  src/Captura/Windows/MainWindow.xaml.cs
  src/Captura/Windows/TrayConfigWindow.xaml
  src/Captura/Windows/TrayConfigWindow.xaml.cs
Labels: enhancement
